### ISSUE TITLE
Alert attribute not taken into accont

### ISSUE THREAD

**Issue by roiKosmic** [SteveyO/Hue-Emulator#5]
Hello,
Is it normal the alert attribute is not supported ?
Possible values are select, lselect and none
Emulator is answering OK but bulb not refreshing.

Have you plan to support it ?

**Comment by SteveyO** [comment]
Hi,
I have not developed any bulb effects as of yet,  i.e. transition times, alerts, colour loops.
I currently do not have time to implement these so it wont be done in the near future,  but in 3-4 months I will evaluate it.  I would like to introduce transition times at some point.
Steve

**Comment by roiKosmic** [comment]
Ok thanks for your feedback.
Vincent

**Comment by manta103g** [comment]
Hi Steve  @SteveyO ping

Just testing your excellent Hue Emulator, trying to guess how to PUT  Hue API XML body message
to be send to your server since none default (Javascript / Json) webpage is provided.

Help file in html opens as html source not webpage.
Does your help file serve as PUT JSON XML Hue Api message sending tool, alike
API debug tool by Philips 
(webpage featuring 2 windows, first for PUT body messages and second window to get GET responses from Hue bridge server)

Thank you

Darius

**Comment by SteveyO** [comment]
Hi Darius,

In future please can you open new github issues for your questions, as this has nothing to do with the 'Alert Attribute' issue.

Regarding your PUT question, I have responded on the developer forum:
http://www.developers.meethue.com/content/how-contact-developer-hue-emulator-windows-add-hue-api-xml-post-url-feature-test-api-line

No, the help files are just static HTML pages,  there is no way to perform any PUTs, or GETs from here.   It should be explained on the above link, use an HTTP client.
Regards
Steve
