### ISSUE TITLE
Emulator-Hue mismatch w.r.t. username

### ISSUE THREAD

**Issue by Cellcote** [SteveyO/Hue-Emulator#8]
Hi,

I have used the emulator to create an App, however, when testing it in an actual Hue lightning kit, I found out that there is a restriction on the length of the username (length >= 10) which is not enforced by the emulator. In the emulator, everything would be OK and I would get the response saying I need to press the link button. Anyways, this is the error received from the Hue:

[{"error":{"type":7,"address":"/username","description":"invalid value,  <username>, for parameter, username"}}]

**Comment by SteveyO** [comment]
I have just tried this and yes you are right,  this is a bug in the emulator,   I forgot to apply the 10 character username restriction.  Thanks for reporting it.

I will fix this in the next version whenever that may be.
Steve

**Comment by SteveyO** [comment]
In the current version of the Emulator (HueEmulator-v0.5.jar) it is no longer possible to create custom usernames,  so this username restriction no long applies (even though it was fixed in the previous version).
FYI - In case you are not aware,  later this year (or early January 2016), the Philips hue bridge will no longer allow custom whitelist username creation,  so this is the reason for this change.
